#USE DB FRESHER
USE fresher;

#CREATE TABLE 1ST->
CREATE TABLE STUDENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(22)NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
CONTACT_NUM BIGINT NOT NULL);

#INSERT DATA ON STUDENT TABLE
INSERT INTO STUDENT(NAME, EMAIL,CONTACT_NUM)VALUES("tejas darekar","tejasdarekar@gmail.com",8238738337),("deep thorat","deepthorat@gmail.com",7828553423),("akshay","akshaydeshmukh@gmail.com",8896625662),("vinay salunkhe","vinaysalunkhe@gmail.com",9227128614);

#CREATE TABLE 2ND->
CREATE TABLE placement(
Id INT PRIMARY KEY AUTO_INCREMENT,
COMPANY_NAME VARCHAR(20) NOT NULL,
PACKAGE INT NOT NULL,
STUDENT_ID INT ,
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ON DELETE CASCADE);

#INSERT DATA ON placement TABLE
INSERT INTO placement(COMPANY_NAME, PACKAGE,STUDENT_ID)VALUES("INFOSYS",12,1),("WIPRO",7,2),("PTC",3.5,4),("CAPGEMINI",6.5,3);

SELECT S.NAME,P.COMPANY_NAME,P.PACKAGE
FROM STUDENT S
INNER JOIN placement P 
ON S.ID = P.Id;

desc placement;




