CREATE DATABASE FRESHER;
USE FRESHER;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
ROLLNUM INT NOT NULL UNIQUE,
FNAME VARCHAR(20) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
AGE INT NOT NULL);

DESC STUDENT;

ALTER TABLE STUDENT
ADD COLUMN MARKS INT NOT NULL;

ALTER TABLE STUDENT 
RENAME COLUMN MARKS TO MARK;

ALTER TABLE STUDENT
MODIFY COLUMN ROLLNUM INT(25) NOT NULL;

ALTER TABLE STUDENT 
DROP COLUMN AGE;

INSERT INTO STUDENT(ROLLNUM,FNAME,LNAME,MARK)VALUES(109,"AKSHAY","DESHMUKH",92),(110,"AJAY","JAGTAP",75),(111,"DEEP","THORAT",81),(112,"VINAY","SALUNKHE",88),(113,"AVINASH","JAYPATRE",77);
INSERT INTO STUDENT(ROLLNUM,FNAME,LNAME,MARK)VALUES(107,"AVINASH","JAYPATRE",92),(108,"RAM","THORAT",92);


SELECT * FROM STUDENT;  # ALL TABLE

SELECT * FROM STUDENT WHERE MARK IS NOT NULL; # ALL STUDENT WHERE MSRS IS NULL

SELECT FNAME FROM STUDENT;  # SELECT SPECIFIC COLUNMN

SELECT * FROM STUDENT WHERE MARK=92;  # SELECT STUDENT WHERE MARKS IS 92

SELECT * FROM STUDENT WHERE MARK <80;

SELECT *  FROM STUDENT WHERE MARK =92 ORDER BY MARK;

SELECT * FROM STUDENT WHERE MARK= 92 ORDER BY FNAME DESC;

SELECT * FROM STUDENT WHERE MARK <90 AND MARK>82;

SELECT * FROM STUDENT WHERE MARK=92 OR MARK = 75; 

SELECT * FROM STUDENT WHERE MARK>75 AND FNAME LIKE 'A%';

SELECT * FROM STUDENT WHERE FNAME NOT LIKE "%S%";

SELECT * FROM STUDENT WHERE MARK BETWEEN 70 AND 90;

SELECT * FROM STUDENT WHERE ROLLNUM NOT  BETWEEN 101 AND 105; 

SELECT * FROM STUDENT WHERE ROLLNUM  BETWEEN 101 AND 105; 

SELECT * FROM STUDENT LIMIT 3;

UPDATE STUDENT SET MARK=72 WHERE ID =5;

DELETE FROM STUDENT WHERE ID=5;

