USE TECHNOASSIGNMENET;

CREATE TABLE EMP(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(25) NOT NULL,
DEPARTMENT VARCHAR(25) NOT NULL,
CITY VARCHAR(24) NOT NULL,
SALARY INT NOT NULL);

INSERT INTO EMP(NAME,DEPARTMENT,CITY,SALARY)VALUES("AKSHAY AR","IT","MUMBAI",4.5),("DEEP GR","IT","PUNE",3.5),("HARIT LY","IT","SANGALI",5.5),("VINAY AP","SALES","NASHIK",12),("RAMAN TT","SALES","BARAMATI",9),("VIKAS OR","BPS","NAGPUR",7);

SELECT * FROM EMP;

SELECT * FROM EMP WHERE CITY="PUNE";

SELECT * FROM EMP WHERE CITY="PUNE" AND DEPARTMENT="IT";

SELECT * FROM EMP WHERE CITY="PUNE" OR CITY="MUMBAI";

ALTER TABLE EMP
RENAME COLUMN  SALARYY TO SALARY; 

SELECT * FROM EMP
WHERE SALARY BETWEEN 2.2 AND 5.5;

SELECT * FROM EMP 
WHERE ID BETWEEN 3 AND 5;

SELECT * FROM EMP 
WHERE NAME LIKE "A%";

SELECT * FROM EMP 
WHERE NAME LIKE "%Y";

SELECT * FROM EMP
WHERE NAME LIKE 'A%Y';

SELECT SALARY*1.1 FROM EMP;

SELECT * FROM EMP 
WHERE DEPARTMENT ="IT" AND SALARY >1.2;

ALTER TABLE EMP
MODIFY COLUMN SALARY DOUBLE NOT NULL;

UPDATE EMP SET SALARY="24.6" WHERE ID=2;

SELECT * FROM EMP;

ALTER TABLE EMP
ADD AGE INT NOT NULL;

ALTER TABLE EMP 
DROP COLUMN AGE;

CREATE TABLE DEPARTMENT(
NAME VARCHAR(22) NOT NULL,
ADDR VARCHAR(22) NOT NULL);

TRUNCATE TABLE DEPARTMENT;

DROP TABLE DEPARTMENT;

INSERT INTO EMP(NAME,DEPARTMENT,CITY,SALARY)VALUES(
"APPA","IT","PUNE",22);

SELECT * FROM EMP;

DELETE FROM EMP
WHERE ID=7;



